version: '3.9'

services:
#  mysql:
#    image: mysql:8
#    ports:
#      - 3306:3306
#    volumes:
#      - ~/apps/mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_USER=user
#      - MYSQL_DATABASE=covid

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080